# Analisi dati dei contagi di COVID-19

https://github.com/pcm-dpc/COVID-19

In [1]:
import pandas as pd
import numpy as np
import datetime
from datetime import date
import os.path

## Preparazione

https://pymotw.com/2/datetime/

In [47]:
lista_reg = list( [ 'Abruzzo', 'Basilicata', 'Calabria', 'Campania', 'Emilia-Romagna', 'Friuli Venezia Giulia', 'Lazio', \
             'Liguria', 'Lombardia', 'Marche', 'Molise', 'P.A. Bolzano', 'P.A. Trento', 'Piemonte', 'Puglia', \
             'Sardegna', 'Sicilia', 'Toscana', 'Umbria', "Valle d'Aosta", 'Veneto' ])

In [11]:
root = "dpc-covid19-ita-regioni-"
latest_file = "https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/\
dati-regioni/dpc-covid19-ita-regioni-latest.csv"

github_fmt = "%Y%m%d"
es_fmt = "%Y-%m-%d"

data_dir = "data/"
time_series_dir = "time series/"
reg_dir = "Regioni/"
raw_dir = "raw/"

first_day = datetime.date(year=2020, month=2, day=24)  # 24 febbraio 2020
today = datetime.date.today()
today = datetime.date(year=today.year, month=today.month,
                      day=today.day)  # today
one_day = datetime.timedelta(days=1)

print("first day   :", first_day)
print("today       :", today)
print("passed days :", (today - first_day).days)

first day   : 2020-02-24
today       : 2020-11-10
passed days : 260

In [3]:
def tostr(date,fmt=github_fmt):
    return date.strftime(fmt)

In [4]:
def dropdata(df):
    df.drop(["data","stato","codice_regione","lat","long","note"],axis=1, inplace=True)
    return df

In [5]:
def getfile(date):
    return directory + tostr(date,es_fmt) + ".csv"

## Download

In [ ]:
# impostazione per sovrascrivere i file
overwrite = False

In [6]:
#
directory = data_dir + reg_dir + raw_dir

#
N = (today - first_day).days
k=0
for i in range(N):
    date      = first_day + i*one_day 
    file_path = getfile(date)
    if False == os.path.exists(file_path) and overwrite == False:
        k=k+1
        print("Downloading file (",i+1,"/",N,"): ",tostr(date,es_fmt),end="\r")
        url = 'https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-regioni/'\
        +root+tostr(date,github_fmt)+".csv"
        df  = pd.read_csv(url)
        df = dropdata(df)
        df.to_csv(file_path,index=False)
print("\nDone (downloaded file: ",k,")")

Downloading file ( 260 / 260 ):  2020-11-09
Done (downloaded file:  9 )

In [7]:
# https://stackoverflow.com/questions/1392413/calculating-a-directorys-size-using-python/1392549
def get_size(start_path = '.',unit="bytes"):
    total_size = 0
    for dirpath, dirnames, filenames in os.walk(start_path):
        for f in filenames:
            fp = os.path.join(dirpath, f)
            # skip if it is symbolic link
            if not os.path.islink(fp):
                total_size += os.path.getsize(fp)
    if unit == "bytes" :
        return total_size
    elif unit == "Kb" or unit == "Kilobytes" :
        return total_size/1024

print("Folder size : ",get_size(directory,"Kb")," Kb")

Folder size :  420.2919921875  Kb

## Dataframe di esempio

In [22]:
df = pd.read_csv(getfile(first_day))
df

,denominazione_regione,ricoverati_con_sintomi,terapia_intensiva,totale_ospedalizzati,isolamento_domiciliare,totale_positivi,variazione_totale_positivi,nuovi_positivi,dimessi_guariti,deceduti,casi_da_sospetto_diagnostico,casi_da_screening,totale_casi,tamponi,casi_testati
0,Abruzzo,0,0,0,0,0,0,0,0,0,NaN,NaN,0,5,NaN
1,Basilicata,0,0,0,0,0,0,0,0,0,NaN,NaN,0,0,NaN
2,Calabria,0,0,0,0,0,0,0,0,0,NaN,NaN,0,1,NaN
3,Campania,0,0,0,0,0,0,0,0,0,NaN,NaN,0,10,NaN
4,Emilia-Romagna,10,2,12,6,18,0,18,0,0,NaN,NaN,18,148,NaN
5,Friuli Venezia Giulia,0,0,0,0,0,0,0,0,0,NaN,NaN,0,58,NaN
6,Lazio,1,1,2,0,2,0,2,1,0,NaN,NaN,3,124,NaN
7,Liguria,0,0,0,0,0,0,0,0,0,NaN,NaN,0,1,NaN
8,Lombardia,76,19,95,71,166,0,166,0,6,NaN,NaN,172,1463,NaN
9,Marche,0,0,0,0,0,0,0,0,0,NaN,NaN,0,16,NaN
10,Molise,0,0,0,0,0,0,0,0,0,NaN,NaN,0,0,NaN
11,P.A. Bolzano,0,0,0,0,0,0,0,0,0,NaN,NaN,0,1,NaN
12,P.A. Trento,0,0,0,0,0,0,0,0,0,NaN,NaN,0,3,NaN
13,Piemonte,2,0,2,1,3,0,3,0,0,NaN,NaN,3,141,NaN
14,Puglia,0,0,0,0,0,0,0,0,0,NaN,NaN,0,0,NaN
15,Sardegna,0,0,0,0,0,0,0,0,0,NaN,NaN,0,1,NaN
16,Sicilia,0,0,0,0,0,0,0,0,0,NaN,NaN,0,5,NaN
17,Toscana,0,0,0,0,0,0,0,0,0,NaN,NaN,0,140,NaN
18,Umbria,0,0,0,0,0,0,0,0,0,NaN,NaN,0,0,NaN
19,Valle d'Aosta,0,0,0,0,0,0,0,0,0,NaN,NaN,0,7,NaN
20,Veneto,12,4,16,16,32,0,32,0,1,NaN,NaN,33,2200,NaN

In [25]:
print(list(df["denominazione_regione"]))

['Abruzzo', 'Basilicata', 'Calabria', 'Campania', 'Emilia-Romagna', 'Friuli Venezia Giulia', 'Lazio', 'Liguria', 'Lombardia', 'Marche', 'Molise', 'P.A. Bolzano', 'P.A. Trento', 'Piemonte', 'Puglia', 'Sardegna', 'Sicilia', 'Toscana', 'Umbria', "Valle d'Aosta", 'Veneto']

## Serie storiche

https://www.earthdatascience.org/courses/use-data-open-source-python/use-time-series-data-in-python/date-time-types-in-pandas-python/customize-dates-matplotlib-plots-python/

In [9]:
cols = [ 'ricoverati_con_sintomi' , 'terapia_intensiva' \
        'totale_ospedalizzati', 'isolamento_domiciliare', 'totale_positivi',\
        'variazione_totale_positivi', 'nuovi_positivi', 'dimessi_guariti',\
        'deceduti', 'casi_da_sospetto_diagnostico', 'casi_da_screening',\
        'totale_casi', 'tamponi', 'casi_testati']# + 'denominazione_regione'

In [13]:
data_dir + reg_dir + time_series_dir + cols[0] + ".csv"

'data/Regioni/time series/ricoverati_con_sintomi.csv'

In [46]:
time_series = pd.DataFrame() 
time_series["Data"] = []
for i in lista_reg :
    time_series[ i ] = []
time_series

Empty DataFrame
Columns: [Data, Abruzzo, Basilicata, Calabria, Campania, Emilia-Romagna, Friuli Venezia Giulia, Lazio, Liguria, Lombardia, Marche, Molise, P.A. Bolzano, P.A. Trento, Piemonte, Puglia, Sardegna, Sicilia, Toscana, Umbria, Valle d'Aosta, Veneto]
Index: []

[0 rows x 22 columns]

In [ ]:
# per ogni variabile creo un file con:
# colonne : data
# righe   : regione

# ciclo sulle variabili
for c in cols :
        # ome del file contenente il dataframe
        file_time_series = data_dir + reg_dir + time_series_dir + c + ".csv"
        # controllo se ho già creato questo file
        if True == os.path.exists(file_time_series) or overwrite == False:
            # in caso affermativo lo leggo e lo agggiorno
            time_series = pd.read_csv(file_time_series)
        else :
            # in caso negativo creo da zero il dataframe
            time_series = pd.DataFrame() 
            time_series["Data"] = []
            for i in lista_reg :
                time_series[ i ] = []
        
        # ciclo su tutte le date (mancanti) ed inserisco i dati
        N = (today - first_day).days
        for i in range(N):
            date      = first_day + i*one_day 
            file_path = getfile(date)
            date_str  = tostr(date,es_fmt)
            # cerco se ho già la data
            if date_str not in time_series["Data"] and overwrite == False :
                df = pd.read_csv(file_path)
                time_series
            
            
            if False == os.path.exists(file_path) and overwrite == False:
                k=k+1
                print("Downloading file (",i+1,"/",N,"): ",tostr(date,es_fmt),end="\r")
                url = 'https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-regioni/'\
                +root+tostr(date,github_fmt)+".csv"
                df  = pd.read_csv(url)
                df = dropdata(df)
                df.to_csv(file_path,index=False)
        print("\nDone (downloaded file: ",k,")")
            
            time_series = pd.DataFrame (data, columns = ['First Column Name','Second Column Name',...])